services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: taskq
      POSTGRES_PASSWORD: taskq
      POSTGRES_DB: taskq
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskq"]
      interval: 5s
      timeout: 3s
      retries: 5
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  api:
    build: .
    image: distributed-task-queue-app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://taskq:taskq@db:5432/taskq
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  worker:
    image: distributed-task-queue-app
    command: celery -A app.celery_app worker --loglevel=info -E
    environment:
      DATABASE_URL: postgresql+psycopg2://taskq:taskq@db:5432/taskq
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  flower:
    image: distributed-task-queue-app
    command: celery -A app.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql+psycopg2://taskq:taskq@db:5432/taskq
      REDIS_URL: redis://redis:6379/0
      FLOWER_UNAUTHENTICATED_API: 1
    depends_on:
      redis:
        condition: service_healthy

volumes:
  pgdata: